import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import '../models/monitoring_form_model.dart';
import '../models/house_data_model.dart';

class PdfService {
  static Future<Uint8List> generateReport({
    required MonitoringSession session,
    required List<HouseMonitoringData> houses,
  }) async {
    final font = await PdfGoogleFonts.notoSansDevanagariRegular();
    final doc = pw.Document();

    final dateTime = DateFormat('dd MMM yyyy, HH:mm').format(DateTime.now());

    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Container(
              width: double.infinity,
              color: PdfColor.fromInt(0xFF1B5E20),
              padding: const pw.EdgeInsets.all(16),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text('UP स्वास्थ्य विभाग', style: pw.TextStyle(font: font, fontSize: 20, color: PdfColors.white)),
                  pw.SizedBox(height: 8),
                  pw.Text('दस्तक एवं संचारी रोग नियंत्रण अभियान हेतु घर-घर मॉनीटरिंग', style: pw.TextStyle(font: font, fontSize: 18, color: PdfColors.white)),
                  pw.SizedBox(height: 6),
                  pw.Text('चरण: अप्रैल 2026', style: pw.TextStyle(font: font, fontSize: 14, color: PdfColors.white)),
                ],
              ),
            ),
            pw.SizedBox(height: 16),
            pw.Table(
              border: pw.TableBorder.all(color: PdfColors.grey),
              children: [
                _buildRow(['नाम', session.monitorName], font),
                _buildRow(['पद', session.designation], font),
                _buildRow(['जनपद', session.district], font),
                _buildRow(['तारीख', session.monitoringDate], font),
                _buildRow(['समय', session.monitoringTime], font),
                _buildRow(['ब्लॉक', session.blockName], font),
                _buildRow(['ग्राम / वार्ड', session.villageWardName], font),
                _buildRow(['संस्थान', session.institution], font),
                _buildRow(['उच्च जोखिम क्षेत्र', session.isHighRiskArea], font),
                _buildRow(['क्षेत्र प्रकार', session.areaType], font),
              ],
            ),
            pw.Spacer(),
            pw.Align(
              alignment: pw.Alignment.bottomRight,
              child: pw.Text('Generated by: Dastak Monitoring App — $dateTime', style: pw.TextStyle(font: font, fontSize: 10, color: PdfColors.grey)),
            ),
          ],
        ),
      ),
    );

    // Summary table page
    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4.landscape,
        header: (context) => pw.Padding(
          padding: const pw.EdgeInsets.only(bottom: 10),
          child: pw.Text('घर-घर रिपोर्ट सारांश', style: pw.TextStyle(font: font, fontSize: 16, fontWeight: pw.FontWeight.bold)),
        ),
        footer: (context) => pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text('Generated by Dastak Monitoring App', style: pw.TextStyle(font: font, fontSize: 8)),
            pw.Text('Page ${context.pageNumber}/${context.pagesCount}', style: pw.TextStyle(font: font, fontSize: 8)),
          ],
        ),
        build: (context) => [
          _buildSummaryTable(session, houses, font),
        ],
      ),
    );

    return doc.save();
  }

  static pw.TableRow _buildRow(List<String> values, pw.Font font) {
    return pw.TableRow(children: values.map((value) {
      return pw.Container(
        padding: const pw.EdgeInsets.all(8),
        child: pw.Text(value, style: pw.TextStyle(font: font, fontSize: 10)),
      );
    }).toList());
  }

  static pw.Widget _buildSummaryTable(MonitoringSession session, List<HouseMonitoringData> houses, pw.Font font) {
    const columns = ['Q', 'प्रश्न', 'घर-1', 'घर-2', 'घर-3', 'घर-4', 'घर-5'];
    final rows = <List<String>>[];

    void addRow(String question, List<String> values) {
      rows.add([question, '', ...values]);
    }

    addRow('Q1.1', houses.map((e) => e.q1_1_aware_dastak).toList());
    addRow('Q1.2', houses.map((e) => e.q1_2_source_codes).toList());
    addRow('Q1.3', houses.map((e) => e.q1_3_received_message).toList());
    addRow('Q2.1', houses.map((e) => e.q2_1_asha_visited).toList());
    addRow('Q2.2', houses.map((e) => e.q2_2_asha_info_given).toList());
    addRow('Q2.3', houses.map((e) => e.q2_3_asha_educated_prevention).toList());
    addRow('Q2.4.1', houses.map((e) => e.q2_4_1_asha_educated_treatment).toList());
    addRow('Q2.4.2', houses.map((e) => e.q2_4_2_asha_108_ambulance).toList());
    addRow('Q2.4.3', houses.map((e) => e.q2_4_3_fever_on_visit_day).toList());
    addRow('Q2.4.4', houses.map((e) => e.q2_4_4_asha_advised_hospital).toList());
    addRow('Q2.5', houses.map((e) => e.q2_5_heatwave_message).toList());
    addRow('Q2.5.1', houses.map((e) => e.q2_5_1_mosquito_breeding_info).toList());
    addRow('Q2.5.2', houses.map((e) => e.q2_5_2_mosquito_source_check).toList());
    addRow('Q2.5.3', houses.map((e) => e.q2_5_3_entomological_form).toList());
    addRow('Q2.6.1', houses.map((e) => e.q2_6_1_fever_14days).toList());
    addRow('Q2.6.2', houses.map((e) => e.q2_6_2_kala_azar_info).toList());
    addRow('Q2.7.1', houses.map((e) => e.q2_7_1_tb_symptoms_educated).toList());
    addRow('Q2.7.2', houses.map((e) => e.q2_7_2_tb_patient_identified).toList());
    addRow('Q2.7.3', houses.map((e) => e.q2_7_3_tb_referred_health_center).toList());
    addRow('Q2.7.4', houses.map((e) => e.q2_7_4_tb_treatment_ongoing).toList());
    addRow('Q2.7.5', houses.map((e) => e.q2_7_5_tb_contacts_tested).toList());
    addRow('Q2.7.6', houses.map((e) => e.q2_7_6_tb_positive_contacts_treated).toList());
    addRow('Q2.7.7', houses.map((e) => e.q2_7_7_tb_negative_contacts_treated).toList());
    addRow('Q2.8', houses.map((e) => e.q2_8_filaria_info).toList());
    addRow('Q2.8.1', houses.map((e) => e.q2_8_1_leprosy_symptoms_info).toList());
    addRow('Q2.8.2', houses.map((e) => e.q2_8_2_leprosy_patient_identified).toList());
    addRow('Q2.8.3', houses.map((e) => e.q2_8_3_leprosy_referred).toList());
    addRow('Q2.9', houses.map((e) => e.q2_9_scrub_typhus_info).toList());
    addRow('Q2.10.1', houses.map((e) => e.q2_10_1_total_family_members.toString()).toList());
    addRow('Q2.10.2', houses.map((e) => e.q2_10_2_ili_cases_found.toString()).toList());
    addRow('Q2.10.3', houses.map((e) => e.q2_10_3_ili_not_listed.toString()).toList());
    addRow('Q2.11', houses.map((e) => e.q2_11_sticker_pasted).toList());
    addRow('Q2.12', houses.map((e) => e.q2_12_handwash_demonstrated).toList());
    addRow('Q2.13', houses.map((e) => e.q2_13_abha_id_created).toList());
    addRow('Q3.1', houses.map((e) => e.q3_1_bush_cutting).toList());
    addRow('Q3.2', houses.map((e) => e.q3_2_drain_cleaning).toList());
    addRow('Q3.3', houses.map((e) => e.q3_3_waterlogging_removed).toList());
    addRow('Q3.4', houses.map((e) => e.q3_4_other_cleaning).toList());
    addRow('Q3.5', houses.map((e) => e.q3_5_fogging_done).toList());
    addRow('Q3.6', houses.map((e) => e.q3_6_anti_larval_activity).toList());
    addRow('Q4.1', houses.map((e) => e.q4_1_school_children_educated).toList());
    addRow('Q4.2', houses.map((e) => e.q4_2_school_name_address).toList());
    addRow('Q4.3', houses.map((e) => e.q4_3_heatwave_educated_school).toList());
    addRow('Q5.1', houses.map((e) => e.q5_1_toilet_available).toList());
    addRow('Q5.2', houses.map((e) => e.q5_2_toilet_used_by_all).toList());
    addRow('Q6.1', houses.map((e) => e.q6_1_water_source).toList());
    addRow('Q6.2', houses.map((e) => e.q6_2_water_purification_known).toList());
    addRow('Q7.1', houses.map((e) => e.q7_1_anganwadi_visited).toList());
    addRow('Q7.2', houses.map((e) => e.q7_2_anganwadi_nutrition_advice).toList());
    addRow('Q8.1', houses.map((e) => e.q8_1_disease_prevention_meeting).toList());
    addRow('Q9.1', houses.map((e) => e.q9_1_animal_husbandry).toList());
    addRow('Q9.2', houses.map((e) => e.q9_2_veterinary_contact_info).toList());
    addRow('Q9.3', houses.map((e) => e.q9_3_animals_away_from_residential).toList());
    addRow('Q10.1', houses.map((e) => e.q10_1_farm_exists).toList());
    addRow('Q10.2', houses.map((e) => e.q10_2_farm_sensitized).toList());
    addRow('Q11.1', houses.map((e) => e.q11_1_chemicals_available).toList());
    addRow('Q11.2', houses.map((e) => e.q11_2_cleanliness_proper).toList());
    addRow('Q11.3', houses.map((e) => e.q11_3_fogging_larval_spray).toList());
    addRow('Q11.4', houses.map((e) => e.q11_4_drinking_water_heatwave).toList());
    addRow('Q11.5', houses.map((e) => e.q11_5_school_full_sleeve).toList());
    addRow('Q12.1', houses.map((e) => e.q12_1_e_kavach_entry).toList());
    addRow('Q12.2', houses.map((e) => e.q12_2_line_list_uploaded).toList());
    addRow('Q12.3', houses.map((e) => e.q12_3_udsp_entry_known).toList());
    addRow('Q13.1', houses.map((e) => e.q13_1_high_vector_list_available).toList());
    addRow('Q13.2', houses.map((e) => e.q13_2_list_shared_departments).toList());
    addRow('Q14.1', houses.map((e) => e.q14_1_idsp_vehicle_available).toList());
    addRow('Gram Vikas Adhikari', houses.map((e) => e.gramVikasAdhikariName).toList());

    return pw.Table.fromTextArray(
      headers: columns,
      data: rows,
      headerStyle: pw.TextStyle(font: font, fontWeight: pw.FontWeight.bold, fontSize: 10),
      cellStyle: pw.TextStyle(font: font, fontSize: 9),
      cellAlignment: pw.Alignment.centerLeft,
      headerDecoration: const pw.BoxDecoration(color: PdfColors.grey300),
      oddRowDecoration: const pw.BoxDecoration(color: PdfColors.grey100),
      border: pw.TableBorder.all(color: PdfColors.grey),
    );
  }
}
